# Change these first
owner: TrizaCorporation # Your GitHub organization or username, where this repository lives
repo: Status # The name of this repository

sites:
  - name: T:Riza
    url: https://www.triza.dev
    maxResponseTime: 800
  - name: T:Riza Api
    url: https://api.triza.dev
    maxResponseTime: 800
  - name: T:Riza Forum
    url: https://forums.triza.dev
    maxResponseTime: 800
  - name: RbxVeri
    url: https://verify.triza.dev
    maxResponseTime: 800
  - name: Melody
    url: https://melody.triza.dev
    maxResponseTime: 800
  - name: Melody Test
    url: https://beta.melody.triza.dev
    maxResponseTime: 800
  - name: Roblox
    url: https://www.roblox.com
    maxResponseTime: 800
  - name: Roblox Group Api
    url: https://groups.roblox.com
    maxResponseTime: 800
  - name: Roblox TextFilter Api
    url: https://textfilter.roblox.com
    maxResponseTime: 800
  - name: Roblox DataStore Api
    url: https://gamepersistence.roblox.com
    maxResponseTime: 800
  - name: Cloudflare
    url: https://www.cloudflare.com
    maxResponseTime: 800
  - name: Discord
    url: https://discord.com
    maxResponseTime: 800
  - name: Google
    url: https://www.google.com
    maxResponseTime: 800
    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.triza.dev
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/TrizaCorporation/Status/master/trizastatuslogo.png
  name: T:Riza Status
  introTitle: "Status Page for Tracking all Incidents which relate to T:Riza"
  introMessage: This is a status page which uses **real-time** data from our [GitHub repository](https://github.com/TrizaCorporation/Status).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  theme: dark
workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "*/20 * * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/2 * * * *"
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
