# Change these first
owner: TrizaCorporation # Your GitHub organization or username, where this repository lives
repo: Status # The name of this repository

sites:
  - name: T:Riza Site
    url: https://www.triza.dev
  - name: T:Riza Api
    url: https://api.triza.dev/v1/checkuptime
  - name: Google
    url: https://www.google.com
  - name: Roblox
    url: https://www.roblox.com
    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: beta-status.triza.dev
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: T:Riza Status
  introTitle: "Status Page for Tracking all Incidents which relate to T:Riza"
  introMessage: This is a status page which uses **real-time** data from our [GitHub repository](https://github.com/TrizaCorporation/Status).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
